### ISSUE TITLE
Rubic Score

### ISSUE THREAD

**Issue by Kavit900** [adafflitto/pjs-capstone-lodash#5]
Criteria 1: Functionality
Score Level: 4 Exceeds Expectations

Criteria 2: Code Style - Formatting
Score Level: 3 Meets Expectations

Criteria 3: Code Style - Javascript
Score Level: 3 Meets Expectations

Overall Score: 10/12

Great job! Next Steps would be take a look at the minor comments and approaches mentioned above but overall from my side, I was really impressed with the code quality and functionality.

**Comment by adafflitto** [comment]
Thanks for the feedback! I appreciate the time spent reviewing my code!
